# === SonarCloud ===
sonar.projectKey=ChristianAINA07_Projet_qualimetrie
sonar.organization=christianaina07
sonar.host.url=https://sonarcloud.io

# === Sources ===
sonar.sources=src
sonar.exclusions=**/tests/**,**/node_modules/**,**/public/**

# === Couverture Jest ===
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# === Bloquer si Quality Gate échoue ===
sonar.qualitygate.wait=true